# Após subir o docker-compose, acesse a aplicação em:
# http://<ip-da-maquina>:8080
# Substitua <ip-da-maquina> pelo IP da máquina onde o Docker está rodando.

version: '3.8'

services:
  h2:
    image: oscarfonts/h2
    container_name: bora-comer-h2
    ports:
      - "1521:1521"
      - "81:81"
    environment:
      H2_OPTIONS: "-tcp -tcpAllowOthers -web -webAllowOthers"
    volumes:
      - h2_data:/opt/h2-data

  app:
    image: openjdk:21-jdk
    container_name: bora-comer-app
    depends_on:
      - h2
    volumes:
      - ./target:/app
    working_dir: /app
    command: ["java", "-jar", "bora-comer-0.0.1-SNAPSHOT.jar"]
    environment:
      SPRING_PROFILES_ACTIVE: test
    ports:
      - "8080:8080"

volumes:
  h2_data:
